[package]
name = "graphics2d"
version = "0.1.0"
edition = "2021"

[dependencies]
pollster = "0.4.0"
wgpu = "25.0.0"
winit = { version = "0.30.10", features = [ "rwh_06" ] }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
client = []
server = []

